//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cocinillas.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cocinillas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceite.
        /// </summary>
        internal static string Aceite {
            get {
                return ResourceManager.GetString("Aceite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arroz.
        /// </summary>
        internal static string Arroz {
            get {
                return ResourceManager.GetString("Arroz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azucar.
        /// </summary>
        internal static string Azucar {
            get {
                return ResourceManager.GetString("Azucar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Harina.
        /// </summary>
        internal static string Harina {
            get {
                return ResourceManager.GetString("Harina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Huevo.
        /// </summary>
        internal static string Huevo {
            get {
                return ResourceManager.GetString("Huevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Judias.
        /// </summary>
        internal static string Judias {
            get {
                return ResourceManager.GetString("Judias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lechuga.
        /// </summary>
        internal static string Lechuga {
            get {
                return ResourceManager.GetString("Lechuga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maiz.
        /// </summary>
        internal static string Maiz {
            get {
                return ResourceManager.GetString("Maiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pollo.
        /// </summary>
        internal static string Pollo {
            get {
                return ResourceManager.GetString("Pollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sal.
        /// </summary>
        internal static string Sal {
            get {
                return ResourceManager.GetString("Sal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salmon.
        /// </summary>
        internal static string Salmon {
            get {
                return ResourceManager.GetString("Salmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tomate.
        /// </summary>
        internal static string Tomate {
            get {
                return ResourceManager.GetString("Tomate", resourceCulture);
            }
        }
    }
}
